name: Docker Image Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REGISTRY: lnguyennb
      IMAGE: cicd-lab-backend
      PLATFORM: "linux/amd64,linux/arm64/v8"
      DOCKER_CREDS: ${{ secrets.DOCKER_HUB_CREDENTIALS }}

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - 
        name: Build Docker image and push to Docker Hub
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker buildx build \
            --platform ${{ env.PLATFORM }} \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.sha }} \
            --build-arg REGISTRY_TOKEN=${{ env.DOCKER_CREDS }} \
            -f Dockerfile . \
            --push